### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Zenahr** [redcatbox/CameraVolumes#23]
This is a great package and I was thinking of adding it as a dependency to one of my open-source UE4 community projects (planning phase currently. The idea is to have a robust, AAA-quality dynamic camera stack in the spirit of Dark Souls, Shadow of the Colossus and Nier: Automata).

Therefore I'm asking under what terms your code would be allowed to be added to such an open-source, non-commercial and free project.

I'm planning on releasing my project under MIT.

**Comment by redcatbox** [comment]
Hello.
You can use this code in any kind of your project for free.
I've added LICENSE.
